# Generated by Django 5.0.7 on 2024-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название действия')),
                ('type_action', models.CharField(choices=[('useful', 'useful'), ('pleasant', 'pleasant'), ('award', 'award')], max_length=20, verbose_name='Тип действия')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pleasant', models.BooleanField(blank=True, null=True, verbose_name='Приятная привычка')),
                ('space', models.CharField(max_length=150, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('periodicity', models.PositiveIntegerField(help_text='Количество выполнений - количество дней в неделю (например: 1 - один раз в неделю, 7 - каждый день)', verbose_name='Периодичность выполнения')),
                ('runtime', models.DurationField(verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(verbose_name='Публичность')),
                ('last_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего выполнения')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
