# Generated by Django 5.0.7 on 2024-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='last_date',
        ),
        migrations.AddField(
            model_name='habit',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующего выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(help_text='1 - каждый день, 2 - 1 раз в два дня и т.д., но не менее 1 раза в 7 дней', verbose_name='Периодичность выполнения'),
        ),
    ]
